name: views_old
channels:
  - defaults
  - anaconda
dependencies:
 - python=3.6
 - numpy
 - pandas
 - matplotlib=2.0.2
 - psycopg2
 - sqlalchemy
 - pylint
 - scikit-learn
 - pytables
 - statsmodels
 - seaborn
 - basemap
 - h5py
 - mpi4py
 - numba
 - patsy
 - ipython
 - krb5
 - scipy=0.19
 - sqlite